#!/usr/bin/python3
"""
Factorising file for RSA Challenge
"""
import sys
argv = sys.argv
file = open(argv[1])
current_line = file.readline()


def factorise(dividend):
    """finds the smaller divisor of a number"""
    divisor = 2
    while divisor <= dividend / 2:
        if dividend % divisor == 0:
            return int(divisor)
        divisor += 1
    return 1

while current_line != "\n" and current_line != "":
    dividend = int(current_line.strip())
    small_factor = factorise(dividend)
    print(f"{dividend:.0f}={(dividend/small_factor):.0f}*{small_factor:.0f}")
    current_line = file.readline()

